apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: devsecops-monitor
  namespace: devsecops
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: devsecops-app
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
